In [1]:
import keras
keras.__version__

Using TensorFlow backend.
C:\Users\1821005\Anaconda3\envs\sotuken\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\1821005\Anaconda3\envs\sotuken\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\1821005\Anaconda3\envs\sotuken\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\1821005\Anaconda3\envs\sot

'2.3.1'

In [4]:
from keras.models import load_model

model = load_model('vgg16_predict_flatten.h5')
model.summary()  # As a reminder.


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 7, 7, 512)         14714688  
_________________________________________________________________
flatten_3 (Flatten)          (None, 25088)             0         
Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________


C:\Users\1821005\Anaconda3\envs\sotuken\lib\site-packages\keras\engine\saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [10]:
"""
import os
files = os.listdir("Desktop/myFolder")
myfile = 'filename.txt'

for filename in files:
    if filename == myfile:
        continue
"""

'\nimport os\nfiles = os.listdir("Desktop/myFolder")\nmyfile = \'filename.txt\'\n\nfor filename in files:\n    if filename == myfile:\n        continue\n'

In [43]:
#vgg16モデルに合わせて入力画像を前処理
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np

img_path_1 = "C:/Users/1821005/Downloads/imagedb/images/test_00003.png"
img_path_2 = "C:/Users/1821005/Downloads/imagedb/images/test_00010.png"
img_path_3 = "C:/Users/1821005/Downloads/imagedb/images/test_00021.png"
img_path_4 = "C:/Users/1821005/Downloads/imagedb/images/test_00027.png"
img_path_5 = "C:/Users/1821005/Downloads/imagedb/images/test_00044.png"
img_path_6 = "C:/Users/1821005/Downloads/imagedb/images/test_00052.png"
#ターゲット(画像)へのローカルパス

        
#画像を読み込む　:imgはサイズが224*224のPIL画像(Pythonで画像を処理するためのライブラリ)
img = image.load_img(img_path_1, target_size=(224,224))
img2 = image.load_img(img_path_2, target_size=(224,224))
img3 = image.load_img(img_path_3, target_size=(224,224))
img4 = image.load_img(img_path_4, target_size=(224,224))
img5 = image.load_img(img_path_5, target_size=(224,224))
img6 = image.load_img(img_path_6, target_size=(224,224))



#xは形状が(224,224，3)のfloat32型のNumPy配列
a = image.img_to_array(img)
b = image.img_to_array(img2)
c = image.img_to_array(img3)
d = image.img_to_array(img4)
e = image.img_to_array(img5)
f = image.img_to_array(img6)

#この配列がサイズが(1,224,224,3)のバッチに変換するために次元を追加
a = np.expand_dims(a, axis=0)
b = np.expand_dims(b, axis=0)
c = np.expand_dims(c, axis=0)
d = np.expand_dims(d, axis=0)
e = np.expand_dims(e, axis=0)
f = np.expand_dims(f, axis=0)

#バッチの前処理(チャンネルごとに色を正規化）
a = preprocess_input(a)
b = preprocess_input(b)
c = preprocess_input(c)
d = preprocess_input(d)
e = preprocess_input(e)
f = preprocess_input(f)

#予測ベクトルを人が読める形にデコード
preds = model.predict(a)
preds1 = model.predict(b)
preds2 = model.predict(c)
preds3 = model.predict(d)
preds4 = model.predict(e)
preds5 = model.predict(f)

In [44]:
preds.shape

(1, 25088)

In [45]:
preds
preds1
preds2
preds3
preds4
preds5

array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [51]:
preds5

array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [47]:
preds2

array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32)