In [33]:
import csv

csv_file = open("/content/test_vector0.csv", "r", encoding="ms932", errors="", newline="" )
#リスト形式
f = csv.reader(csv_file, delimiter=",", doublequote=True, lineterminator="\r\n", quotechar='"', skipinitialspace=True)
# header = next(f)
# print(header)
# for row in f:
#     #rowはList
#     #row[0]で必要な項目を取得することができる
#     print(row)

In [34]:
a = list(f)

In [35]:
len(a)

10000

In [36]:
len(a[0])

1000

In [37]:
a = [[float(x) for x in y] for y in a]

In [38]:
a[0][0]

0.9282364

In [39]:
import numpy as np

a = np.array(a)

In [40]:
a.dtype

dtype('float64')

In [41]:
a.shape

(10000, 1000)

In [42]:
import pickle

with open('test_vector0.pickle', 'wb') as f:
  pickle.dump(a, f)

In [43]:
with open('test_vector0.pickle', 'rb') as f:
  b = pickle.load(f)

In [44]:
b

array([[0.9282364 , 0.9121494 , 0.868789  , ..., 0.8702936 , 0.84567416,
        0.57850736],
       [0.92269075, 0.8839689 , 0.8585708 , ..., 0.8341607 , 0.7261881 ,
        0.4061524 ],
       [0.94081736, 0.8050675 , 0.8663063 , ..., 0.77491003, 0.5501399 ,
        0.4806694 ],
       ...,
       [0.9315147 , 0.73319   , 0.7722766 , ..., 0.83128726, 0.97467273,
        0.54782516],
       [0.90655464, 0.8585419 , 0.7298855 , ..., 0.9125082 , 0.967808  ,
        0.29768026],
       [0.93451977, 0.8099219 , 0.9043329 , ..., 0.74508715, 0.8830536 ,
        0.32076946]])

In [51]:
from sklearn.cluster import KMeans

kmeans = KMeans(10)
kmeans.fit(a)
result = kmeans.transform(a)

-140928.0537318267

In [56]:
kmeans.labels_

array([9, 3, 4, ..., 9, 7, 2], dtype=int32)

In [65]:
from sklearn.decomposition import PCA

pca = PCA(2)
pca.fit(a)
aa = pca.transform(a)
pca.explained_variance_ratio_

array([0.23777175, 0.13735778])

In [ ]:
import matplotlib.pyplot as plt

for i in range(10):
  target = kmeans.labels_ == i
  plt.scatter(aa[target, 0], aa[target, 1])