# ソート方法の練習

In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 100, size = 20)

In [3]:
a

array([74, 26, 46, 94, 27, 87, 69, 78, 76, 64,  8, 35,  7, 36, 36, 85, 51,
        1, 27, 32])

In [4]:
np.sort(a)

array([ 1,  7,  8, 26, 27, 27, 32, 35, 36, 36, 46, 51, 64, 69, 74, 76, 78,
       85, 87, 94])

In [7]:
np.argsort(a)

array([17, 12, 10,  1,  4, 18, 19, 11, 14, 13,  2, 16,  9,  6,  0,  8,  7,
       15,  5,  3])

*インデックス，元々配列の入っていた順番の番号のこと*

In [9]:
b = np.array([1, 3, 2])

In [8]:
np.argsort(b)

array([0, 2, 1])